name: 'Setup wasmtime-py CI'
runs:
  using: "composite"
  steps:
  - run: rustup target add wasm32-unknown-unknown wasm32-wasi
    shell: bash
  - run: cargo install wasm-tools --git https://github.com/bytecodealliance/wasm-tools --no-default-features --features component
    shell: bash
  - uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - run: python ci/download-wasmtime.py
    shell: bash
  - run: python ci/build-rust.py
    shell: bash
  - run: pip install -e ".[testing]"
    shell: bash
